package ir.malek.textanalysis.srl;

import java.util.ArrayList;

import org.apache.commons.lang3.builder.HashCodeBuilder;

public class ExVerbs {
	/*
	 * private class Verb{ String verb=""; String nve="";//فعل یار String
	 * vprt="";// };
	 */
	ArrayList<Verb> verbList = new ArrayList<Verb>();
	ArrayList<Verb> verbListKardan = new ArrayList<Verb>();
	ArrayList<Verb> notPassive = new ArrayList<Verb>();
	ArrayList<Verb> compoundList = new ArrayList<Verb>();
	
	public ExVerbs() {

		Verb item = new Verb("اتفاق", "افتادن");
		verbList.add(item);
		item = new Verb("آب", "افتادن");
		verbList.add(item);
		item = new Verb("پس", "افتادن");
		verbList.add(item);
		item = new Verb("گود", "افتادن");
		verbList.add(item);
		item = new Verb("پا", "افتادن");
		verbList.add(item);
		item = new Verb("کار", "افتادن");
		verbList.add(item);
		item = new Verb("گل", "انداختن");
		verbList.add(item);
		item = new Verb("پوست", "انداختن");
		verbList.add(item);
		item = new Verb("بند", "آمدن");
		verbList.add(item);
		item = new Verb("پیش", "آمدن");
		verbList.add(item);
		item = new Verb("رو", "آمدن");
		verbList.add(item);
		item = new Verb("جوش", "آمدن");
		verbList.add(item);
		item = new Verb("زیاد", "آمدن");
		verbList.add(item);
		item = new Verb("سر", "آمدن");
		verbList.add(item);
		item = new Verb("قوام", "آمدن");
		verbList.add(item);
		item = new Verb("کش", "آمدن");
		verbList.add(item);
		item = new Verb("کم", "آمدن");
		verbList.add(item);
		item = new Verb("حساب", "آمدن");
		verbList.add(item);
		item = new Verb("خاطر", "آمدن");
		verbList.add(item);
		item = new Verb("خود", "آمدن");
		verbList.add(item);
		item = new Verb("میان", "آمدن");
		verbList.add(item);
		item = new Verb("آب", "آوردن");
		verbList.add(item);
		item = new Verb("بالا", "آوردن");
		verbList.add(item);
		item = new Verb("اسلام", "آوردن");
		verbList.add(item);
		item = new Verb("گوشت", "آوردن");
		verbList.add(item);
		item = new Verb("پیه", "آوردن");
		verbList.add(item);
		item = new Verb("لک", "آوردن");
		verbList.add(item);
		item = new Verb("ناز", "آوردن");
		verbList.add(item);
		item = new Verb("جان", "باختن");
		verbList.add(item);
		item = new Verb("رنگ", "باختن");
		verbList.add(item);
		item = new Verb("پینه", "بستن");
		verbList.add(item);
		item = new Verb("نطفه", "بستن");
		verbList.add(item);
		item = new Verb("یخ", "بستن");
		verbList.add(item);
		item = new Verb("انجام", "پذیرفتن");
		verbList.add(item);
		item = new Verb("پایان", "پذیرفتن");
		verbList.add(item);
		item = new Verb("تحقق", "پذیرفتن");
		verbList.add(item);
		item = new Verb("خاتمه", "پذیرفتن");
		verbList.add(item);
		item = new Verb("سامان", "پذیرفتن");
		verbList.add(item);
		item = new Verb("صورت", "پذیرفتن");
		verbList.add(item);
		item = new Verb("بخیه", "خوردن");
		verbList.add(item);
		item = new Verb("برگشت", "خوردن");
		verbList.add(item);
		item = new Verb("پیچ", "خوردن");
		verbList.add(item);
		item = new Verb("تراش", "خوردن");
		verbList.add(item);
		item = new Verb("ترک", "خوردن");
		verbList.add(item);
		item = new Verb("تلو", "خوردن");
		verbList.add(item);
		item = new Verb("جر", "خوردن");
		verbList.add(item);
		item = new Verb("چاک", "خوردن");
		verbList.add(item);
		item = new Verb("چشم", "خوردن");
		verbList.add(item);
		item = new Verb("چین", "خوردن");
		verbList.add(item);
		item = new Verb("دست", "خوردن");
		verbList.add(item);
		item = new Verb("زمین", "خوردن");
		verbList.add(item);
		item = new Verb("سرما", "خوردن");
		verbList.add(item);
		item = new Verb("شکاف", "خوردن");
		verbList.add(item);
		item = new Verb("غم", "خوردن");
		verbList.add(item);
		item = new Verb("فر", "خوردن");
		verbList.add(item);
		item = new Verb("کلید", "خوردن");
		verbList.add(item);
		item = new Verb("گیج", "خوردن");
		verbList.add(item);
		item = new Verb("ورق", "خوردن");
		verbList.add(item);
		item = new Verb("وصله", "خوردن");
		verbList.add(item);
		item = new Verb("هم", "خوردن");
		verbList.add(item);
		item=new Verb("آنتن","دادن"); 
		verbList.add(item);
		item = new Verb("روی", "دادن");
		verbList.add(item);
		item = new Verb("صدا", "دادن");
		verbList.add(item);
		item = new Verb("رخ", "دادن");
		verbList.add(item);
		item = new Verb("نتیجه", "دادن");
		verbList.add(item);
		item = new Verb("احتمال", "داشتن");
		verbList.add(item);
		item = new Verb("امکان", "داشتن");
		verbList.add(item);
		item = new Verb("حقیقت", "داشتن");
		verbList.add(item);
		item = new Verb("مشابهت", "داشتن");
		verbList.add(item);
		item = new Verb("اسیب", "دیدن");
		verbList.add(item);
		item = new Verb("صدمه", "دیدن");
		verbList.add(item);
		item = new Verb("سر", "رسیدن");
		verbList.add(item);
		item = new Verb("قتل", "رسیدن");
		verbList.add(item);
		item = new Verb("پس", "رفتن");
		verbList.add(item);
		item = new Verb("تحلیل", "رفتن");
		verbList.add(item);
		// item=new Verb("خواب","رفتن"); verbList.add(item);
		item = new Verb("سر", "رفتن");
		verbList.add(item);
		item = new Verb("فروش", "رفتن");
		verbList.add(item);
		item = new Verb("گیج", "رفتن");
		verbList.add(item);
		item = new Verb("هدر", "رفتن");
		verbList.add(item);
		item = new Verb("بین", "رفتن");
		verbList.add(item);
		item = new Verb("پیش", "رفتن");
		verbList.add(item);
		item = new Verb("دست", "رفتن");
		verbList.add(item);
		item = new Verb("کف", "رفتن");
		verbList.add(item);
		item = new Verb("باد", "رفتن");
		verbList.add(item);
		item = new Verb("وا", "رفتن");
		verbList.add(item);
		item = new Verb("برق", "زدن");
		verbList.add(item);
		item = new Verb("پرپر", "زدن");
		verbList.add(item);
		item = new Verb("تاول", "زدن");
		verbList.add(item);
		item = new Verb("پیچ", "زدن");
		verbList.add(item);
		item = new Verb("جا", "زدن");
		verbList.add(item);
		item = new Verb("جرقه", "زدن");
		verbList.add(item);
		item = new Verb("جوانه", "زدن");
		verbList.add(item);
		item = new Verb("جوش", "زدن");
		verbList.add(item);
		// item=new Verb("چرت","زدن"); verbList.add(item);
		item = new Verb("زبانه", "زدن");
		verbList.add(item);
		item = new Verb("زنگ", "زدن");
		verbList.add(item);
		item = new Verb("سفیدک", "زدن");
		verbList.add(item);
		item = new Verb("سوسو", "زدن");
		verbList.add(item);
		item = new Verb("شعله", "زدن");
		verbList.add(item);
		item = new Verb("شکرک", "زدن");
		verbList.add(item);
		item = new Verb("شکوفه", "زدن");
		verbList.add(item);
		item = new Verb("شوره", "زدن");
		verbList.add(item);
		item = new Verb("غل", "زدن");
		verbList.add(item);
		item = new Verb("فلاش", "زدن");
		verbList.add(item);
		item = new Verb("فلش", "زدن");
		verbList.add(item);
		item = new Verb("قارچ", "زدن");
		verbList.add(item);
		item = new Verb("قلقل", "زدن");
		verbList.add(item);
		item = new Verb("کپک", "زدن");
		verbList.add(item);
		item = new Verb("کهیر", "زدن");
		verbList.add(item);
		item = new Verb("کورسو", "زدن");
		verbList.add(item);
		// item=new Verb("گند","زدن"); verbList.add(item);
		// item=new Verb("مژه","زدن"); verbList.add(item);
		// item=new Verb("نفس","زدن"); verbList.add(item);
		item = new Verb("نفس نفس", "زدن");
		verbList.add(item);
		item = new Verb("یخ", "زدن");
		verbList.add(item);
		item = new Verb("جان", "سپردن");
		verbList.add(item);
		item = new Verb("آه", "کشیدن");
		verbList.add(item);
		item = new Verb("تیر", "کشیدن");
		verbList.add(item);
		item = new Verb("خرناس", "کشیدن");
		verbList.add(item);
		item = new Verb("خرناسه", "کشیدن");
		verbList.add(item);
		item = new Verb("خمیازه", "کشیدن");
		verbList.add(item);
		item = new Verb("دم", "کشیدن");
		verbList.add(item);
		item = new Verb("زوزه", "کشیدن");
		verbList.add(item);
		item = new Verb("شعله", "کشیدن");
		verbList.add(item);
		item = new Verb("فامت", "کشیدن");
		verbList.add(item);
		item = new Verb("نفس", "کشیدن");
		verbList.add(item);
		item = new Verb("نم", "کشیدن");
		verbList.add(item);
		item = new Verb("الو", "گرفتن");
		verbList.add(item);
		item = new Verb("آتش", "گرفتن");
		verbList.add(item);
		item = new Verb("انجام", "گرفتن");
		verbList.add(item);
		item = new Verb("آفتاب", "گرفتن");
		verbList.add(item);
		item = new Verb("بارش", "گرفتن");
		verbList.add(item);
		item = new Verb("بالا", "گرفتن");
		verbList.add(item);
		item = new Verb("بو", "گرفتن");
		verbList.add(item);
		item = new Verb("پایان", "گرفتن");
		verbList.add(item);
		item = new Verb("ثبات", "گرفتن");
		verbList.add(item);
		item = new Verb("درخشش", "گرفتن");
		verbList.add(item);
		item = new Verb("درد", "گرفتن");
		verbList.add(item);
		item = new Verb("ریتم", "گرفتن");
		verbList.add(item);
		item = new Verb("صورت", "گرفتن");
		verbList.add(item);
		item = new Verb("در", "گرفتن");
		verbList.add(item);
		item = new Verb("قرار", "گرفتن");
		verbList.add(item);
		item = new Verb("ته", "نشستن");
		verbList.add(item);
		item = new Verb("پا", "نشستن");
		verbList.add(item);
		item = new Verb("پای", "نشستن");
		verbList.add(item);
		item = new Verb("اصلاح", "یافتن");
		verbList.add(item);
		item = new Verb("افزایش", "یافتن");
		verbList.add(item);
		item = new Verb("التیام", "یافتن");
		verbList.add(item);
		item = new Verb("انبساط", "یافتن");
		verbList.add(item);
		item = new Verb("انتشار", "یافتن");
		verbList.add(item);
		item = new Verb("انتقال", "یافتن");
		verbList.add(item);
		item = new Verb("انجام", "یافتن");
		verbList.add(item);
		item = new Verb("پایان", "یافتن");
		verbList.add(item);
		item = new Verb("تالیف", "یافتن");
		verbList.add(item);
		item = new Verb("تحول", "یافتن");
		verbList.add(item);
		item = new Verb("تحقق", "یافتن");
		verbList.add(item);
		item = new Verb("تداوم", "یافتن");
		verbList.add(item);
		item = new Verb("ترقی", "یافتن");
		verbList.add(item);
		item = new Verb("ترمیم", "یافتن");
		verbList.add(item);
		item = new Verb("تسریع", "یافتن");
		verbList.add(item);
		item = new Verb("تسلی", "یافتن");
		verbList.add(item);
		item = new Verb("تشدید", "یافتن");
		verbList.add(item);
		item = new Verb("تضعیف", "یافتن");
		verbList.add(item);
		item = new Verb("تعدیل", "یافتن");
		verbList.add(item);
		item = new Verb("تکثیر", "یافتن");
		verbList.add(item);
		item = new Verb("تکوین", "یافتن");
		verbList.add(item);
		item = new Verb("تنظیم", "یافتن");
		verbList.add(item);
		item = new Verb("تولد", "یافتن");
		verbList.add(item);
		item = new Verb("خاتمه", "یافتن");
		verbList.add(item);
		item = new Verb("سازماندهی", "یافتن");
		verbList.add(item);
		item = new Verb("سامان", "یافتن");
		verbList.add(item);
		item = new Verb("صورت", "یافتن");
		verbList.add(item);
		item = new Verb("علاج", "یافتن");
		verbList.add(item);
		item = new Verb("فیصله", "یافتن");
		verbList.add(item);
		item = new Verb("قطعیت", "یافتن");
		verbList.add(item);
		item = new Verb("کاستی", "یافتن");
		verbList.add(item);
		item = new Verb("کاهش", "یافتن");
		verbList.add(item);
		item = new Verb("گشایش", "یافتن");
		verbList.add(item);
		item = new Verb("لزوم", "یافتن");
		verbList.add(item);
		item = new Verb("وفات", "یافتن");
		verbList.add(item);
		item = new Verb("ولادت", "یافتن");
		verbList.add(item);
		item = new Verb("متولد", "شدن");
		verbList.add(item);
		item = new Verb("مواجه", "شدن");
		verbList.add(item);
		item = new Verb("روبه رو", "شدن");
		verbList.add(item);

		item = new Verb("", "پلاسیدن");
		verbList.add(item);
		item = new Verb("", "ترکیدن");
		verbList.add(item);
		item = new Verb("", "خاریدن");
		verbList.add(item);
		item = new Verb("", "خراشیدن");
		verbList.add(item);
		item = new Verb("", "خشکیدن");
		verbList.add(item);
		item = new Verb("", "درخشیدن");
		verbList.add(item);
		item = new Verb("", "سفتن");
		verbList.add(item);
		item = new Verb("", "سنبیدن");
		verbList.add(item);
		item = new Verb("", "سوختن");
		verbList.add(item);
		item = new Verb("", "شکافتن");
		verbList.add(item);
		item = new Verb("", "شکستن");
		verbList.add(item);
		item = new Verb("", "فرسودن");
		verbList.add(item);
		// item=new Verb("","فشردن"); verbList.add(item);
		item = new Verb("", "کاستن");
		verbList.add(item);
		item = new Verb("", "کوفتن");
		verbList.add(item);
		item = new Verb("", "گداختن");
		verbList.add(item);
		item = new Verb("", "گرفتن");
		verbList.add(item);

		item = new Verb("اتصالی", "کردن");
		verbListKardan.add(item);
		item = new Verb("ارتحال", "کردن");
		verbListKardan.add(item);
		item = new Verb("ارتعاش", "کردن");
		verbListKardan.add(item);
		item = new Verb("افول", "کردن");
		verbListKardan.add(item);
		item = new Verb("آبسه", "کردن");
		verbListKardan.add(item);
		item = new Verb("آماس", "کردن");
		verbListKardan.add(item);
		item = new Verb("بخار", "کردن");
		verbListKardan.add(item);
		item = new Verb("برکت", "کردن");
		verbListKardan.add(item);
		item = new Verb("بیداد", "کردن");
		verbListKardan.add(item);
		item = new Verb("پف", "کردن");
		verbListKardan.add(item);
		item = new Verb("تب", "کردن");
		verbListKardan.add(item);
		item = new Verb("تشعشع", "کردن");
		verbListKardan.add(item);
		item = new Verb("تشنج", "کردن");
		verbListKardan.add(item);
		item = new Verb("تلاطم", "کردن");
		verbListKardan.add(item);
		item = new Verb("تیک تاک", "کردن");
		verbListKardan.add(item);
		item = new Verb("خارش", "کردن");
		verbListKardan.add(item);
		item = new Verb("خس خس", "کردن");
		verbListKardan.add(item);
		item = new Verb("خسوف", "کردن");
		verbListKardan.add(item);
		item = new Verb("خوشه", "کردن");
		verbListKardan.add(item);
		item = new Verb("زوال", "کردن");
		verbListKardan.add(item);
		item = new Verb("ارتحال", "کردن");
		verbListKardan.add(item);
		item = new Verb("سوسو", "کردن");
		verbListKardan.add(item);
		item = new Verb("عرق", "کردن");
		verbListKardan.add(item);
		item = new Verb("عفونت", "کردن");
		verbListKardan.add(item);
		item = new Verb("عیب", "کردن");
		verbListKardan.add(item);
		item = new Verb("غروب", "کردن");
		verbListKardan.add(item);
		item = new Verb("غژغژ", "کردن");
		verbListKardan.add(item);
		item = new Verb("غش", "کردن");
		verbListKardan.add(item);
		item = new Verb("غلیان", "کردن");
		verbListKardan.add(item);
		item = new Verb("فایده", "کردن");
		verbListKardan.add(item);
		item = new Verb("فروپاشی", "کردن");
		verbListKardan.add(item);
		item = new Verb("فروکش", "کردن");
		verbListKardan.add(item);
		item = new Verb("فزونی", "کردن");
		verbListKardan.add(item);
		item = new Verb("فوت", "کردن");
		verbListKardan.add(item);
		item = new Verb("قل قل", "کردن");
		verbListKardan.add(item);
		item = new Verb("قولنج", "کردن");
		verbListKardan.add(item);
		item = new Verb("کسوف", "کردن");
		verbListKardan.add(item);
		item = new Verb("گل", "کردن");
		verbListKardan.add(item);
		item = new Verb("لرز", "کردن");
		verbListKardan.add(item);
		item = new Verb("میوه", "کردن");
		verbListKardan.add(item);
		item = new Verb("نشست", "کردن");
		verbListKardan.add(item);
		item = new Verb("وزوز", "کردن");
		verbListKardan.add(item);
		item = new Verb("وفات", "کردن");
		verbListKardan.add(item);
		item = new Verb("یخ", "کردن");
		verbListKardan.add(item);

		item = new Verb("واقع", "کردن");
		verbListKardan.add(item);
		
		item = new Verb("گوش", "رسیدن");
		verbListKardan.add(item);
		// not passive:
		item = new Verb("وارد", "شدن");
		notPassive.add(item);
		item = new Verb("باعث", "شدن");
		notPassive.add(item);
		item = new Verb("منجر", "شدن");
		notPassive.add(item);
		
		// compoundList
		item = new Verb("وجود", "امدن");
		compoundList.add(item);
		item = new Verb("وجود", "اوردن");
		compoundList.add(item);
		item = new Verb("شرط", "بستن");
		compoundList.add(item);
		item = new Verb("مقابله", "برخاستن");
		compoundList.add(item);
		item = new Verb("گام", "برداشتن");
		compoundList.add(item);
		item = new Verb("دارا", "بودن");
		compoundList.add(item);
		item = new Verb("قرار", "بودن");
		compoundList.add(item);
		item = new Verb("وقوع", "پیوستن");
		compoundList.add(item);
		item = new Verb("نماز", "خواندن");
		compoundList.add(item);
		item = new Verb("مشابهت", "داشتن");
		compoundList.add(item);
		item = new Verb("مجادله", "داشتن");
		compoundList.add(item);
		item = new Verb("زبان", "راندن");
		compoundList.add(item);
		item = new Verb("اجازه", "دادن");
		compoundList.add(item);
		item = new Verb("انتقال", "دادن");
		compoundList.add(item);
		item = new Verb("پیشنهاد", "دادن");
		compoundList.add(item);
		item = new Verb("خبر", "دادن");
		compoundList.add(item);
		item = new Verb("دست", "دادن");
		compoundList.add(item);
		item = new Verb("قرار", "دادن");
		compoundList.add(item);
		item = new Verb("غذا", "دادن");
		compoundList.add(item);
		item = new Verb("هشدار", "دادن");
		compoundList.add(item);
		item = new Verb("هشدارباش", "دادن");
		compoundList.add(item);
		item = new Verb("قصد", "داشتن");
		compoundList.add(item);
		item = new Verb("نظر", "داشتن");
		compoundList.add(item);
		item = new Verb("پرواز", "درامدن");
		compoundList.add(item);
		item = new Verb("لرزه", "درآوردن");
		compoundList.add(item);
		item = new Verb("لرزه", "دراوردن");
		compoundList.add(item);
		item = new Verb("نظم", "درآوردن");
		compoundList.add(item);
		item = new Verb("کنترل", "دراوردن");
		compoundList.add(item);
		item = new Verb("نظم", "دراوردن");
		compoundList.add(item);
		item = new Verb("تاثیر", "گذاشتن");
		compoundList.add(item);
		item = new Verb("کنار", "گذاشتن");
		compoundList.add(item);
		item = new Verb("فشار", "گذاشتن");
		compoundList.add(item);
		item = new Verb("قیمت", "گذاشتن");
		compoundList.add(item);
		item = new Verb("ارشیو", "کردن");
		compoundList.add(item);
		item = new Verb("اعلام", "کردن");
		compoundList.add(item);
		item = new Verb("بایگانی", "کردن");
		compoundList.add(item);
		item = new Verb("پس انداز", "کردن");
		compoundList.add(item);
		item = new Verb("پیاده", "کردن");
		compoundList.add(item);
		item = new Verb("تشکیک", "کردن");
		compoundList.add(item);
		item = new Verb("خنثی", "کردن");
		compoundList.add(item);
		item = new Verb("شک", "کردن");
		compoundList.add(item);
		item = new Verb("ضمیمه", "کردن");
		compoundList.add(item);
		item = new Verb("خراب", "شدن");
		compoundList.add(item);
		item = new Verb("فاسد", "شدن");
		compoundList.add(item);
		item = new Verb("زحمت", "کشیدن");
		compoundList.add(item);
		item = new Verb("نشان", "گرفتن");
		compoundList.add(item);
		item = new Verb("خدمت", "گرفتن");
		compoundList.add(item);
		item = new Verb("تسلیت", "گفتن");
		compoundList.add(item);
		
	}

	public boolean exist1(String string1, String string2) {
		Verb item = new Verb(string1, string2);
		if (verbList.contains(item))
			return true;
		else
			return false;
	}

	public boolean exist2(String string1, String string2) {
		Verb item = new Verb(string1, string2);
		if (verbListKardan.contains(item))
			return true;
		else
			return false;

	}

	public boolean ExistinNonPassive(String string1, String string2) {
		Verb item = new Verb(string1, string2);
		if (notPassive.contains(item))
			return true;
		else
			return false;

	}
	public boolean ExistInCompound(String string1,String string2){
		Verb item = new Verb(string1, string2);
		if (verbListKardan.contains(item))
			return true;
		if (compoundList.contains(item))
			return true;
		if (verbList.contains(item))
			return true;
		return false;
	}

}

class Verb {
	String firstPart = "";
	String verb = "";

	Verb(String firstPart, String verb) {
		this.firstPart = firstPart;
		this.verb = verb;
	}

	@Override
	public boolean equals(Object object) {
		if (object == null || getClass() != object.getClass())
			return false;
		Verb cverb = (Verb) object;
		if (firstPart.equals(cverb.firstPart) && verb.equals(cverb.verb))
			return true;
		else
			return false;
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(17, 31). // two randomly chosen prime numbers
		append(firstPart).append(verb).toHashCode();
	}
}